# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 942)
        MainWindow.setMinimumSize(QtCore.QSize(836, 558))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pipeLineFrame = QtWidgets.QFrame(self.centralwidget)
        self.pipeLineFrame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pipeLineFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pipeLineFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pipeLineFrame.setObjectName("pipeLineFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pipeLineFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphFrame = QtWidgets.QFrame(self.pipeLineFrame)
        self.graphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphFrame.setObjectName("graphFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.graphFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.componentLabel = QtWidgets.QLabel(self.graphFrame)
        self.componentLabel.setObjectName("componentLabel")
        self.gridLayout_7.addWidget(self.componentLabel, 0, 0, 1, 2)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.graphFrame)
        self.doubleSpinBox_2.setDecimals(5)
        self.doubleSpinBox_2.setMaximum(999999999.0)
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_7.addWidget(self.doubleSpinBox_2, 7, 1, 1, 1)
        self.n_init = QtWidgets.QSpinBox(self.graphFrame)
        self.n_init.setProperty("value", 10)
        self.n_init.setObjectName("n_init")
        self.gridLayout_7.addWidget(self.n_init, 3, 0, 1, 1)
        self.componentMin = QtWidgets.QSpinBox(self.graphFrame)
        self.componentMin.setMinimum(1)
        self.componentMin.setMaximum(999999999)
        self.componentMin.setProperty("value", 5)
        self.componentMin.setObjectName("componentMin")
        self.gridLayout_7.addWidget(self.componentMin, 1, 0, 1, 1)
        self.pairwiseLabel = QtWidgets.QLabel(self.graphFrame)
        self.pairwiseLabel.setObjectName("pairwiseLabel")
        self.gridLayout_7.addWidget(self.pairwiseLabel, 6, 0, 1, 1)
        self.componentMax = QtWidgets.QSpinBox(self.graphFrame)
        self.componentMax.setMaximum(999999999)
        self.componentMax.setProperty("value", 9)
        self.componentMax.setObjectName("componentMax")
        self.gridLayout_7.addWidget(self.componentMax, 1, 1, 1, 1)
        self.restartLabel = QtWidgets.QLabel(self.graphFrame)
        self.restartLabel.setObjectName("restartLabel")
        self.gridLayout_7.addWidget(self.restartLabel, 2, 0, 1, 1)
        self.GMMButton = QtWidgets.QPushButton(self.graphFrame)
        self.GMMButton.setEnabled(False)
        self.GMMButton.setObjectName("GMMButton")
        self.gridLayout_7.addWidget(self.GMMButton, 4, 0, 1, 2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphFrame)
        self.doubleSpinBox.setDecimals(5)
        self.doubleSpinBox.setMaximum(999999999.0)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_7.addWidget(self.doubleSpinBox, 7, 0, 1, 1)
        self.scaleLabel = QtWidgets.QLabel(self.graphFrame)
        self.scaleLabel.setObjectName("scaleLabel")
        self.gridLayout_7.addWidget(self.scaleLabel, 6, 1, 1, 1)
        self.graphcutButton = QtWidgets.QPushButton(self.graphFrame)
        self.graphcutButton.setEnabled(False)
        self.graphcutButton.setObjectName("graphcutButton")
        self.gridLayout_7.addWidget(self.graphcutButton, 8, 0, 1, 2)
        self.gridLayout_2.addWidget(self.graphFrame, 10, 0, 1, 1)
        self.clusteringBox = QtWidgets.QComboBox(self.pipeLineFrame)
        self.clusteringBox.setObjectName("clusteringBox")
        self.clusteringBox.addItem("")
        self.clusteringBox.addItem("")
        self.gridLayout_2.addWidget(self.clusteringBox, 9, 0, 1, 1)
        self.featureExtractionLabel = QtWidgets.QLabel(self.pipeLineFrame)
        self.featureExtractionLabel.setObjectName("featureExtractionLabel")
        self.gridLayout_2.addWidget(self.featureExtractionLabel, 5, 0, 1, 1)
        self.cosegmentationLabel = QtWidgets.QLabel(self.pipeLineFrame)
        self.cosegmentationLabel.setToolTip("")
        self.cosegmentationLabel.setObjectName("cosegmentationLabel")
        self.gridLayout_2.addWidget(self.cosegmentationLabel, 8, 0, 1, 1)
        self.superpixelCalculationLabel = QtWidgets.QLabel(self.pipeLineFrame)
        self.superpixelCalculationLabel.setObjectName("superpixelCalculationLabel")
        self.gridLayout_2.addWidget(self.superpixelCalculationLabel, 0, 0, 1, 1)
        self.featureVectorOptionsFrame = QtWidgets.QFrame(self.pipeLineFrame)
        self.featureVectorOptionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.featureVectorOptionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.featureVectorOptionsFrame.setObjectName("featureVectorOptionsFrame")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.featureVectorOptionsFrame)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.currentLabel = QtWidgets.QLabel(self.featureVectorOptionsFrame)
        self.currentLabel.setObjectName("currentLabel")
        self.gridLayout_19.addWidget(self.currentLabel, 3, 0, 1, 1)
        self.featureSelected = QtWidgets.QComboBox(self.featureVectorOptionsFrame)
        self.featureSelected.setObjectName("featureSelected")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.setItemText(7, "")
        self.gridLayout_19.addWidget(self.featureSelected, 3, 1, 1, 2)
        self.Saturation = QtWidgets.QCheckBox(self.featureVectorOptionsFrame)
        self.Saturation.setObjectName("Saturation")
        self.gridLayout_19.addWidget(self.Saturation, 0, 1, 1, 1)
        self.HSV = QtWidgets.QCheckBox(self.featureVectorOptionsFrame)
        self.HSV.setObjectName("HSV")
        self.gridLayout_19.addWidget(self.HSV, 1, 0, 1, 1)
        self.Hog = QtWidgets.QCheckBox(self.featureVectorOptionsFrame)
        self.Hog.setObjectName("Hog")
        self.gridLayout_19.addWidget(self.Hog, 0, 2, 1, 1)
        self.HueSat = QtWidgets.QCheckBox(self.featureVectorOptionsFrame)
        self.HueSat.setObjectName("HueSat")
        self.gridLayout_19.addWidget(self.HueSat, 1, 1, 1, 1)
        self.RGB = QtWidgets.QCheckBox(self.featureVectorOptionsFrame)
        self.RGB.setChecked(True)
        self.RGB.setObjectName("RGB")
        self.gridLayout_19.addWidget(self.RGB, 0, 0, 1, 1)
        self.Sift = QtWidgets.QCheckBox(self.featureVectorOptionsFrame)
        self.Sift.setObjectName("Sift")
        self.gridLayout_19.addWidget(self.Sift, 2, 1, 1, 1)
        self.Hue = QtWidgets.QCheckBox(self.featureVectorOptionsFrame)
        self.Hue.setObjectName("Hue")
        self.gridLayout_19.addWidget(self.Hue, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.featureVectorOptionsFrame, 6, 0, 1, 1)
        self.superpixelCalculationFrame = QtWidgets.QFrame(self.pipeLineFrame)
        self.superpixelCalculationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.superpixelCalculationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.superpixelCalculationFrame.setObjectName("superpixelCalculationFrame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.superpixelCalculationFrame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.sigmaLabel = QtWidgets.QLabel(self.superpixelCalculationFrame)
        self.sigmaLabel.setObjectName("sigmaLabel")
        self.gridLayout_10.addWidget(self.sigmaLabel, 4, 1, 1, 1)
        self.compactnessLabel = QtWidgets.QLabel(self.superpixelCalculationFrame)
        self.compactnessLabel.setObjectName("compactnessLabel")
        self.gridLayout_10.addWidget(self.compactnessLabel, 4, 0, 1, 1)
        self.compactnessSpinBox = QtWidgets.QDoubleSpinBox(self.superpixelCalculationFrame)
        self.compactnessSpinBox.setDecimals(5)
        self.compactnessSpinBox.setMaximum(1000000000.0)
        self.compactnessSpinBox.setProperty("value", 10.0)
        self.compactnessSpinBox.setObjectName("compactnessSpinBox")
        self.gridLayout_10.addWidget(self.compactnessSpinBox, 5, 0, 1, 1)
        self.superpixelQuantityLabel = QtWidgets.QLabel(self.superpixelCalculationFrame)
        self.superpixelQuantityLabel.setMaximumSize(QtCore.QSize(132, 17))
        self.superpixelQuantityLabel.setObjectName("superpixelQuantityLabel")
        self.gridLayout_10.addWidget(self.superpixelQuantityLabel, 2, 0, 1, 1)
        self.iterationsLabel = QtWidgets.QLabel(self.superpixelCalculationFrame)
        self.iterationsLabel.setObjectName("iterationsLabel")
        self.gridLayout_10.addWidget(self.iterationsLabel, 2, 1, 1, 1)
        self.superpixelButton = QtWidgets.QPushButton(self.superpixelCalculationFrame)
        self.superpixelButton.setEnabled(False)
        self.superpixelButton.setObjectName("superpixelButton")
        self.gridLayout_10.addWidget(self.superpixelButton, 6, 0, 1, 1)
        self.superpixelSpinBox = QtWidgets.QSpinBox(self.superpixelCalculationFrame)
        self.superpixelSpinBox.setMinimum(1)
        self.superpixelSpinBox.setMaximum(999999999)
        self.superpixelSpinBox.setProperty("value", 500)
        self.superpixelSpinBox.setObjectName("superpixelSpinBox")
        self.gridLayout_10.addWidget(self.superpixelSpinBox, 3, 0, 1, 1)
        self.iterationsSpinBox = QtWidgets.QSpinBox(self.superpixelCalculationFrame)
        self.iterationsSpinBox.setMaximum(999999999)
        self.iterationsSpinBox.setProperty("value", 10)
        self.iterationsSpinBox.setObjectName("iterationsSpinBox")
        self.gridLayout_10.addWidget(self.iterationsSpinBox, 3, 1, 1, 1)
        self.sigmaSpinBox = QtWidgets.QDoubleSpinBox(self.superpixelCalculationFrame)
        self.sigmaSpinBox.setDecimals(5)
        self.sigmaSpinBox.setMaximum(1000000000.0)
        self.sigmaSpinBox.setProperty("value", 0.0)
        self.sigmaSpinBox.setObjectName("sigmaSpinBox")
        self.gridLayout_10.addWidget(self.sigmaSpinBox, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.superpixelCalculationFrame, 4, 0, 1, 1)
        self.kmeansFrame = QtWidgets.QFrame(self.pipeLineFrame)
        self.kmeansFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kmeansFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kmeansFrame.setObjectName("kmeansFrame")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.kmeansFrame)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.k1 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k1.setStyleSheet("color: black")
        self.k1.setObjectName("k1")
        self.gridLayout_17.addWidget(self.k1, 3, 0, 1, 1)
        self.k3 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k3.setStyleSheet("color: red")
        self.k3.setObjectName("k3")
        self.gridLayout_17.addWidget(self.k3, 7, 0, 1, 1)
        self.k2 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k2.setStyleSheet("color: white")
        self.k2.setObjectName("k2")
        self.gridLayout_17.addWidget(self.k2, 4, 0, 1, 1)
        self.kmeansButton = QtWidgets.QPushButton(self.kmeansFrame)
        self.kmeansButton.setEnabled(False)
        self.kmeansButton.setObjectName("kmeansButton")
        self.gridLayout_17.addWidget(self.kmeansButton, 1, 0, 1, 2)
        self.clusterFGLabel = QtWidgets.QLabel(self.kmeansFrame)
        self.clusterFGLabel.setObjectName("clusterFGLabel")
        self.gridLayout_17.addWidget(self.clusterFGLabel, 2, 0, 1, 4)
        self.clusterLabel = QtWidgets.QLabel(self.kmeansFrame)
        self.clusterLabel.setObjectName("clusterLabel")
        self.gridLayout_17.addWidget(self.clusterLabel, 1, 2, 1, 1)
        self.kclustervalue = QtWidgets.QSpinBox(self.kmeansFrame)
        self.kclustervalue.setMinimum(2)
        self.kclustervalue.setMaximum(16)
        self.kclustervalue.setObjectName("kclustervalue")
        self.gridLayout_17.addWidget(self.kclustervalue, 1, 3, 1, 1)
        self.k4 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k4.setStyleSheet("color: lime")
        self.k4.setObjectName("k4")
        self.gridLayout_17.addWidget(self.k4, 8, 0, 1, 1)
        self.k5 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k5.setStyleSheet("color: blue")
        self.k5.setObjectName("k5")
        self.gridLayout_17.addWidget(self.k5, 3, 1, 1, 1)
        self.k6 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k6.setStyleSheet("color: yellow")
        self.k6.setObjectName("k6")
        self.gridLayout_17.addWidget(self.k6, 4, 1, 1, 1)
        self.k7 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k7.setStyleSheet("color: cyan")
        self.k7.setObjectName("k7")
        self.gridLayout_17.addWidget(self.k7, 7, 1, 1, 1)
        self.k8 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k8.setStyleSheet("color: magenta")
        self.k8.setObjectName("k8")
        self.gridLayout_17.addWidget(self.k8, 8, 1, 1, 1)
        self.k9 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k9.setStyleSheet("color: silver")
        self.k9.setObjectName("k9")
        self.gridLayout_17.addWidget(self.k9, 3, 2, 1, 1)
        self.k10 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k10.setStyleSheet("color: grey")
        self.k10.setObjectName("k10")
        self.gridLayout_17.addWidget(self.k10, 4, 2, 1, 1)
        self.k11 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k11.setStyleSheet("color: maroon")
        self.k11.setObjectName("k11")
        self.gridLayout_17.addWidget(self.k11, 7, 2, 1, 1)
        self.k12 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k12.setStyleSheet("color: olive")
        self.k12.setObjectName("k12")
        self.gridLayout_17.addWidget(self.k12, 8, 2, 1, 1)
        self.k13 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k13.setStyleSheet("color : green")
        self.k13.setObjectName("k13")
        self.gridLayout_17.addWidget(self.k13, 3, 3, 1, 1)
        self.k14 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k14.setStyleSheet("color: purple")
        self.k14.setObjectName("k14")
        self.gridLayout_17.addWidget(self.k14, 4, 3, 1, 1)
        self.k15 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k15.setStyleSheet("color: teal")
        self.k15.setObjectName("k15")
        self.gridLayout_17.addWidget(self.k15, 7, 3, 1, 1)
        self.k16 = QtWidgets.QCheckBox(self.kmeansFrame)
        self.k16.setStyleSheet("color: navy")
        self.k16.setObjectName("k16")
        self.gridLayout_17.addWidget(self.k16, 8, 3, 1, 1)
        self.gridLayout_2.addWidget(self.kmeansFrame, 11, 0, 1, 1)
        self.featureVectorFrame = QtWidgets.QFrame(self.pipeLineFrame)
        self.featureVectorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.featureVectorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.featureVectorFrame.setObjectName("featureVectorFrame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.featureVectorFrame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.blockSize = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.blockSize.setMinimum(1)
        self.blockSize.setMaximum(999999999)
        self.blockSize.setProperty("value", 16)
        self.blockSize.setObjectName("blockSize")
        self.gridLayout_12.addWidget(self.blockSize, 12, 1, 1, 1)
        self.colorLabel2 = QtWidgets.QLabel(self.featureVectorFrame)
        self.colorLabel2.setObjectName("colorLabel2")
        self.gridLayout_12.addWidget(self.colorLabel2, 5, 0, 1, 1)
        self.cellHogLabel = QtWidgets.QLabel(self.featureVectorFrame)
        self.cellHogLabel.setObjectName("cellHogLabel")
        self.gridLayout_12.addWidget(self.cellHogLabel, 13, 1, 1, 1)
        self.hogBins = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.hogBins.setMaximum(9999999)
        self.hogBins.setProperty("value", 9)
        self.hogBins.setObjectName("hogBins")
        self.gridLayout_12.addWidget(self.hogBins, 16, 0, 1, 1)
        self.binsHogLabel = QtWidgets.QLabel(self.featureVectorFrame)
        self.binsHogLabel.setObjectName("binsHogLabel")
        self.gridLayout_12.addWidget(self.binsHogLabel, 15, 0, 1, 1)
        self.cellSize = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.cellSize.setMinimum(1)
        self.cellSize.setMaximum(999999999)
        self.cellSize.setProperty("value", 8)
        self.cellSize.setObjectName("cellSize")
        self.gridLayout_12.addWidget(self.cellSize, 14, 1, 1, 1)
        self.blockHogLabel = QtWidgets.QLabel(self.featureVectorFrame)
        self.blockHogLabel.setObjectName("blockHogLabel")
        self.gridLayout_12.addWidget(self.blockHogLabel, 11, 1, 1, 1)
        self.winSize = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.winSize.setMinimum(1)
        self.winSize.setMaximum(999999999)
        self.winSize.setProperty("value", 32)
        self.winSize.setObjectName("winSize")
        self.gridLayout_12.addWidget(self.winSize, 12, 0, 1, 1)
        self.blockStride = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.blockStride.setMinimum(1)
        self.blockStride.setMaximum(999999999)
        self.blockStride.setProperty("value", 8)
        self.blockStride.setObjectName("blockStride")
        self.gridLayout_12.addWidget(self.blockStride, 14, 0, 1, 1)
        self.graph_button = QtWidgets.QPushButton(self.featureVectorFrame)
        self.graph_button.setEnabled(False)
        self.graph_button.setObjectName("graph_button")
        self.gridLayout_12.addWidget(self.graph_button, 17, 1, 1, 1)
        self.blockStrideHogLabel = QtWidgets.QLabel(self.featureVectorFrame)
        self.blockStrideHogLabel.setObjectName("blockStrideHogLabel")
        self.gridLayout_12.addWidget(self.blockStrideHogLabel, 13, 0, 1, 1)
        self.siftlabel = QtWidgets.QLabel(self.featureVectorFrame)
        self.siftlabel.setObjectName("siftlabel")
        self.gridLayout_12.addWidget(self.siftlabel, 8, 0, 1, 1)
        self.HHist = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.HHist.setMaximum(360)
        self.HHist.setProperty("value", 5)
        self.HHist.setObjectName("HHist")
        self.gridLayout_12.addWidget(self.HHist, 3, 0, 1, 1)
        self.HSSHist = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.HSSHist.setMinimum(2)
        self.HSSHist.setMaximum(360)
        self.HSSHist.setProperty("value", 3)
        self.HSSHist.setObjectName("HSSHist")
        self.gridLayout_12.addWidget(self.HSSHist, 1, 1, 1, 1)
        self.entropyLabel_1 = QtWidgets.QLabel(self.featureVectorFrame)
        self.entropyLabel_1.setObjectName("entropyLabel_1")
        self.gridLayout_12.addWidget(self.entropyLabel_1, 2, 1, 1, 1)
        self.SHist = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.SHist.setMinimum(2)
        self.SHist.setMaximum(360)
        self.SHist.setProperty("value", 3)
        self.SHist.setObjectName("SHist")
        self.gridLayout_12.addWidget(self.SHist, 6, 0, 1, 1)
        self.entropyLabel_2 = QtWidgets.QLabel(self.featureVectorFrame)
        self.entropyLabel_2.setObjectName("entropyLabel_2")
        self.gridLayout_12.addWidget(self.entropyLabel_2, 5, 1, 1, 1)
        self.histogramButton = QtWidgets.QPushButton(self.featureVectorFrame)
        self.histogramButton.setEnabled(False)
        self.histogramButton.setObjectName("histogramButton")
        self.gridLayout_12.addWidget(self.histogramButton, 17, 0, 1, 1)
        self.siftKeyPoint = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.siftKeyPoint.setMinimum(1)
        self.siftKeyPoint.setMaximum(999999999)
        self.siftKeyPoint.setProperty("value", 32)
        self.siftKeyPoint.setObjectName("siftKeyPoint")
        self.gridLayout_12.addWidget(self.siftKeyPoint, 9, 0, 1, 1)
        self.windowHogLabel = QtWidgets.QLabel(self.featureVectorFrame)
        self.windowHogLabel.setObjectName("windowHogLabel")
        self.gridLayout_12.addWidget(self.windowHogLabel, 11, 0, 1, 1)
        self.colorLabel1 = QtWidgets.QLabel(self.featureVectorFrame)
        self.colorLabel1.setObjectName("colorLabel1")
        self.gridLayout_12.addWidget(self.colorLabel1, 2, 0, 1, 1)
        self.SentropyCheckBox = QtWidgets.QCheckBox(self.featureVectorFrame)
        self.SentropyCheckBox.setText("")
        self.SentropyCheckBox.setObjectName("SentropyCheckBox")
        self.gridLayout_12.addWidget(self.SentropyCheckBox, 6, 1, 1, 1)
        self.HSHHist = QtWidgets.QSpinBox(self.featureVectorFrame)
        self.HSHHist.setMinimum(2)
        self.HSHHist.setMaximum(360)
        self.HSHHist.setProperty("value", 5)
        self.HSHHist.setObjectName("HSHHist")
        self.gridLayout_12.addWidget(self.HSHHist, 1, 0, 1, 1)
        self.HentropyCheckBox = QtWidgets.QCheckBox(self.featureVectorFrame)
        self.HentropyCheckBox.setText("")
        self.HentropyCheckBox.setObjectName("HentropyCheckBox")
        self.gridLayout_12.addWidget(self.HentropyCheckBox, 3, 1, 1, 1)
        self.colorLabel3 = QtWidgets.QLabel(self.featureVectorFrame)
        self.colorLabel3.setObjectName("colorLabel3")
        self.gridLayout_12.addWidget(self.colorLabel3, 0, 0, 1, 1)
        self.colorLabel4 = QtWidgets.QLabel(self.featureVectorFrame)
        self.colorLabel4.setObjectName("colorLabel4")
        self.gridLayout_12.addWidget(self.colorLabel4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.featureVectorFrame, 7, 0, 1, 1)
        self.gridLayout.addWidget(self.pipeLineFrame, 0, 0, 1, 1)
        self.fileFrame = QtWidgets.QFrame(self.centralwidget)
        self.fileFrame.setMaximumSize(QtCore.QSize(350, 350))
        self.fileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fileFrame.setObjectName("fileFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fileFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.treeView = QtWidgets.QTreeView(self.fileFrame)
        self.treeView.setObjectName("treeView")
        self.gridLayout_4.addWidget(self.treeView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.fileFrame, 2, 0, 1, 1)
        self.imageListFrame = QtWidgets.QFrame(self.centralwidget)
        self.imageListFrame.setMaximumSize(QtCore.QSize(16777215, 350))
        self.imageListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageListFrame.setObjectName("imageListFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.imageListFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.imageListFrame)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 720, 93))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_4)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_24.addWidget(self.listWidget, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.imageListFrame, 2, 1, 1, 2)
        self.view = QtWidgets.QTabWidget(self.centralwidget)
        self.view.setObjectName("view")
        self.drawTab = QtWidgets.QWidget()
        self.drawTab.setObjectName("drawTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.drawTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.drawTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 460, 723))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout_6.addWidget(self.image, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.view.addTab(self.drawTab, "")
        self.superpixelTab = QtWidgets.QWidget()
        self.superpixelTab.setObjectName("superpixelTab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.superpixelTab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.superpixelTab)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 460, 723))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.superImage = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.superImage.setText("")
        self.superImage.setObjectName("superImage")
        self.gridLayout_16.addWidget(self.superImage, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_15.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.view.addTab(self.superpixelTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 460, 723))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.uncertainty_image = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.uncertainty_image.setText("")
        self.uncertainty_image.setObjectName("uncertainty_image")
        self.gridLayout_22.addWidget(self.uncertainty_image, 0, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_23.addWidget(self.scrollArea_5, 0, 0, 1, 1)
        self.view.addTab(self.tab, "")
        self.resultsTab = QtWidgets.QWidget()
        self.resultsTab.setObjectName("resultsTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.resultsTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.resultsTab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 460, 723))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.result_image = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.result_image.setText("")
        self.result_image.setObjectName("result_image")
        self.gridLayout_14.addWidget(self.result_image, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_8.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.view.addTab(self.resultsTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 460, 723))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.compare_image = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.compare_image.setText("")
        self.compare_image.setObjectName("compare_image")
        self.gridLayout_28.addWidget(self.compare_image, 0, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_27.addWidget(self.scrollArea_6, 0, 0, 1, 1)
        self.view.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.view, 0, 1, 1, 1)
        self.settingFrame = QtWidgets.QFrame(self.centralwidget)
        self.settingFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.settingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingFrame.setObjectName("settingFrame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.settingFrame)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.progressBoxLabel = QtWidgets.QLabel(self.settingFrame)
        self.progressBoxLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progressBoxLabel.setObjectName("progressBoxLabel")
        self.gridLayout_13.addWidget(self.progressBoxLabel, 12, 0, 1, 1)
        self.superpixelLabel = QtWidgets.QLabel(self.settingFrame)
        self.superpixelLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.superpixelLabel.setObjectName("superpixelLabel")
        self.gridLayout_13.addWidget(self.superpixelLabel, 2, 0, 1, 1)
        self.exportSettings = QtWidgets.QPushButton(self.settingFrame)
        self.exportSettings.setObjectName("exportSettings")
        self.gridLayout_13.addWidget(self.exportSettings, 15, 0, 1, 1)
        self.uncertaintyFrame = QtWidgets.QFrame(self.settingFrame)
        self.uncertaintyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.uncertaintyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.uncertaintyFrame.setObjectName("uncertaintyFrame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.uncertaintyFrame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.edgeRadioButton = QtWidgets.QRadioButton(self.uncertaintyFrame)
        self.edgeRadioButton.setEnabled(False)
        self.edgeRadioButton.setCheckable(True)
        self.edgeRadioButton.setChecked(True)
        self.edgeRadioButton.setObjectName("edgeRadioButton")
        self.gridLayout_11.addWidget(self.edgeRadioButton, 0, 0, 1, 1)
        self.nodeRadioButton = QtWidgets.QRadioButton(self.uncertaintyFrame)
        self.nodeRadioButton.setEnabled(False)
        self.nodeRadioButton.setCheckable(True)
        self.nodeRadioButton.setObjectName("nodeRadioButton")
        self.gridLayout_11.addWidget(self.nodeRadioButton, 0, 1, 1, 1)
        self.graphRadioButton = QtWidgets.QRadioButton(self.uncertaintyFrame)
        self.graphRadioButton.setEnabled(False)
        self.graphRadioButton.setObjectName("graphRadioButton")
        self.gridLayout_11.addWidget(self.graphRadioButton, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.uncertaintyFrame, 5, 0, 1, 1)
        self.graphCutModeFrame = QtWidgets.QFrame(self.settingFrame)
        self.graphCutModeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphCutModeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphCutModeFrame.setObjectName("graphCutModeFrame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.graphCutModeFrame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.bwRadioButton = QtWidgets.QRadioButton(self.graphCutModeFrame)
        self.bwRadioButton.setEnabled(False)
        self.bwRadioButton.setChecked(True)
        self.bwRadioButton.setObjectName("bwRadioButton")
        self.gridLayout_18.addWidget(self.bwRadioButton, 0, 0, 1, 1)
        self.bRadioButton = QtWidgets.QRadioButton(self.graphCutModeFrame)
        self.bRadioButton.setEnabled(False)
        self.bRadioButton.setObjectName("bRadioButton")
        self.gridLayout_18.addWidget(self.bRadioButton, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.graphCutModeFrame, 7, 0, 1, 1)
        self.markingLabel = QtWidgets.QLabel(self.settingFrame)
        self.markingLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.markingLabel.setObjectName("markingLabel")
        self.gridLayout_13.addWidget(self.markingLabel, 0, 0, 1, 1)
        self.superpixelSettingFrame = QtWidgets.QFrame(self.settingFrame)
        self.superpixelSettingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.superpixelSettingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.superpixelSettingFrame.setObjectName("superpixelSettingFrame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.superpixelSettingFrame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.drawRadioButton = QtWidgets.QRadioButton(self.superpixelSettingFrame)
        self.drawRadioButton.setEnabled(False)
        self.drawRadioButton.setChecked(True)
        self.drawRadioButton.setObjectName("drawRadioButton")
        self.gridLayout_9.addWidget(self.drawRadioButton, 0, 0, 1, 1)
        self.histogramRadioButton = QtWidgets.QRadioButton(self.superpixelSettingFrame)
        self.histogramRadioButton.setEnabled(False)
        self.histogramRadioButton.setObjectName("histogramRadioButton")
        self.gridLayout_9.addWidget(self.histogramRadioButton, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.superpixelSettingFrame, 3, 0, 1, 1)
        self.markingFrame = QtWidgets.QFrame(self.settingFrame)
        self.markingFrame.setMaximumSize(QtCore.QSize(16777215, 360))
        self.markingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.markingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.markingFrame.setObjectName("markingFrame")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.markingFrame)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.fgRadioButton = QtWidgets.QRadioButton(self.markingFrame)
        self.fgRadioButton.setChecked(True)
        self.fgRadioButton.setObjectName("fgRadioButton")
        self.gridLayout_20.addWidget(self.fgRadioButton, 0, 0, 1, 1)
        self.bgRadioButton = QtWidgets.QRadioButton(self.markingFrame)
        self.bgRadioButton.setObjectName("bgRadioButton")
        self.gridLayout_20.addWidget(self.bgRadioButton, 0, 1, 1, 1)
        self.clearMarkingsButton = QtWidgets.QPushButton(self.markingFrame)
        self.clearMarkingsButton.setEnabled(False)
        self.clearMarkingsButton.setObjectName("clearMarkingsButton")
        self.gridLayout_20.addWidget(self.clearMarkingsButton, 3, 0, 1, 2)
        self.gridLayout_13.addWidget(self.markingFrame, 1, 0, 1, 1)
        self.importSettings = QtWidgets.QPushButton(self.settingFrame)
        self.importSettings.setObjectName("importSettings")
        self.gridLayout_13.addWidget(self.importSettings, 14, 0, 1, 1)
        self.progressFrame = QtWidgets.QFrame(self.settingFrame)
        self.progressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressFrame.setObjectName("progressFrame")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.progressFrame)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.cosegmentationProgress = QtWidgets.QLabel(self.progressFrame)
        self.cosegmentationProgress.setObjectName("cosegmentationProgress")
        self.gridLayout_21.addWidget(self.cosegmentationProgress, 4, 0, 1, 1)
        self.featureProgress = QtWidgets.QLabel(self.progressFrame)
        self.featureProgress.setObjectName("featureProgress")
        self.gridLayout_21.addWidget(self.featureProgress, 2, 0, 1, 1)
        self.superpixelProgress = QtWidgets.QLabel(self.progressFrame)
        self.superpixelProgress.setObjectName("superpixelProgress")
        self.gridLayout_21.addWidget(self.superpixelProgress, 0, 0, 1, 1)
        self.superpixelStatus = QtWidgets.QLabel(self.progressFrame)
        self.superpixelStatus.setStyleSheet("color: red")
        self.superpixelStatus.setObjectName("superpixelStatus")
        self.gridLayout_21.addWidget(self.superpixelStatus, 0, 1, 1, 1)
        self.extractionStatus = QtWidgets.QLabel(self.progressFrame)
        self.extractionStatus.setStyleSheet("color: red")
        self.extractionStatus.setObjectName("extractionStatus")
        self.gridLayout_21.addWidget(self.extractionStatus, 2, 1, 1, 1)
        self.clusteringStatus = QtWidgets.QLabel(self.progressFrame)
        self.clusteringStatus.setStyleSheet("color: red")
        self.clusteringStatus.setObjectName("clusteringStatus")
        self.gridLayout_21.addWidget(self.clusteringStatus, 4, 1, 1, 1)
        self.gridLayout_13.addWidget(self.progressFrame, 13, 0, 1, 1)
        self.uncertaintyLabel = QtWidgets.QLabel(self.settingFrame)
        self.uncertaintyLabel.setObjectName("uncertaintyLabel")
        self.gridLayout_13.addWidget(self.uncertaintyLabel, 4, 0, 1, 1)
        self.graphCutModeLabel = QtWidgets.QLabel(self.settingFrame)
        self.graphCutModeLabel.setObjectName("graphCutModeLabel")
        self.gridLayout_13.addWidget(self.graphCutModeLabel, 6, 0, 1, 1)
        self.clusterModeFrame = QtWidgets.QFrame(self.settingFrame)
        self.clusterModeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clusterModeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clusterModeFrame.setObjectName("clusterModeFrame")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.clusterModeFrame)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.bwkRadioButton = QtWidgets.QRadioButton(self.clusterModeFrame)
        self.bwkRadioButton.setEnabled(False)
        self.bwkRadioButton.setCheckable(True)
        self.bwkRadioButton.setChecked(False)
        self.bwkRadioButton.setObjectName("bwkRadioButton")
        self.gridLayout_25.addWidget(self.bwkRadioButton, 0, 1, 1, 1)
        self.colorRadioButton = QtWidgets.QRadioButton(self.clusterModeFrame)
        self.colorRadioButton.setEnabled(False)
        self.colorRadioButton.setCheckable(True)
        self.colorRadioButton.setChecked(True)
        self.colorRadioButton.setObjectName("colorRadioButton")
        self.gridLayout_25.addWidget(self.colorRadioButton, 0, 2, 1, 1)
        self.gridLayout_13.addWidget(self.clusterModeFrame, 9, 0, 1, 1)
        self.clusterModeLabel = QtWidgets.QLabel(self.settingFrame)
        self.clusterModeLabel.setObjectName("clusterModeLabel")
        self.gridLayout_13.addWidget(self.clusterModeLabel, 8, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.settingFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gt_overlapRadioButton = QtWidgets.QRadioButton(self.frame_2)
        self.gt_overlapRadioButton.setEnabled(False)
        self.gt_overlapRadioButton.setObjectName("gt_overlapRadioButton")
        self.gridLayout_26.addWidget(self.gt_overlapRadioButton, 2, 1, 1, 1)
        self.gt_originalRadioButton = QtWidgets.QRadioButton(self.frame_2)
        self.gt_originalRadioButton.setEnabled(False)
        self.gt_originalRadioButton.setChecked(True)
        self.gt_originalRadioButton.setObjectName("gt_originalRadioButton")
        self.gridLayout_26.addWidget(self.gt_originalRadioButton, 2, 0, 1, 1)
        self.gtpercentage = QtWidgets.QLabel(self.frame_2)
        self.gtpercentage.setObjectName("gtpercentage")
        self.gridLayout_26.addWidget(self.gtpercentage, 0, 1, 1, 1)
        self.overlapLabel = QtWidgets.QLabel(self.frame_2)
        self.overlapLabel.setObjectName("overlapLabel")
        self.gridLayout_26.addWidget(self.overlapLabel, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_2, 11, 0, 1, 1)
        self.gtLabel = QtWidgets.QLabel(self.settingFrame)
        self.gtLabel.setObjectName("gtLabel")
        self.gridLayout_13.addWidget(self.gtLabel, 10, 0, 1, 1)
        self.gridLayout.addWidget(self.settingFrame, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.view.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.componentLabel.setText(_translate("MainWindow", "Component range"))
        self.pairwiseLabel.setText(_translate("MainWindow", "pairwise term scale"))
        self.restartLabel.setText(_translate("MainWindow", "Number of restarts"))
        self.GMMButton.setText(_translate("MainWindow", "Compute GMM and uncertainties"))
        self.scaleLabel.setText(_translate("MainWindow", "scale parameters"))
        self.graphcutButton.setText(_translate("MainWindow", "Graph cut"))
        self.clusteringBox.setItemText(0, _translate("MainWindow", "Graph cut"))
        self.clusteringBox.setItemText(1, _translate("MainWindow", "kmeans clustering"))
        self.featureExtractionLabel.setText(_translate("MainWindow", "Compute feature vectors"))
        self.cosegmentationLabel.setText(_translate("MainWindow", "Co-segmentation"))
        self.superpixelCalculationLabel.setText(_translate("MainWindow", "Superpixel calculation"))
        self.currentLabel.setText(_translate("MainWindow", "Current:"))
        self.featureSelected.setItemText(0, _translate("MainWindow", "RGB"))
        self.featureSelected.setItemText(1, _translate("MainWindow", "HSV"))
        self.featureSelected.setItemText(2, _translate("MainWindow", "Hue"))
        self.featureSelected.setItemText(3, _translate("MainWindow", "Saturation"))
        self.featureSelected.setItemText(4, _translate("MainWindow", "Hue x Saturation"))
        self.featureSelected.setItemText(5, _translate("MainWindow", "Sift"))
        self.featureSelected.setItemText(6, _translate("MainWindow", "Hog"))
        self.Saturation.setText(_translate("MainWindow", "Saturation"))
        self.HSV.setText(_translate("MainWindow", "HSV"))
        self.Hog.setText(_translate("MainWindow", "Hog"))
        self.HueSat.setText(_translate("MainWindow", "Hue x Saturation"))
        self.RGB.setText(_translate("MainWindow", "RGB"))
        self.Sift.setText(_translate("MainWindow", "Sift"))
        self.Hue.setText(_translate("MainWindow", "Hue"))
        self.sigmaLabel.setText(_translate("MainWindow", "Sigma"))
        self.compactnessLabel.setText(_translate("MainWindow", "Compactness"))
        self.superpixelQuantityLabel.setText(_translate("MainWindow", "Superpixel quantity"))
        self.iterationsLabel.setText(_translate("MainWindow", "Max iterations"))
        self.superpixelButton.setText(_translate("MainWindow", "Calculate superpixels"))
        self.k1.setText(_translate("MainWindow", "1"))
        self.k3.setText(_translate("MainWindow", "3"))
        self.k2.setText(_translate("MainWindow", "2"))
        self.kmeansButton.setText(_translate("MainWindow", "kmeans clustering"))
        self.clusterFGLabel.setText(_translate("MainWindow", "clusters part of foreground"))
        self.clusterLabel.setText(_translate("MainWindow", "Clusters:"))
        self.k4.setText(_translate("MainWindow", "4"))
        self.k5.setText(_translate("MainWindow", "5"))
        self.k6.setText(_translate("MainWindow", "6"))
        self.k7.setText(_translate("MainWindow", "7"))
        self.k8.setText(_translate("MainWindow", "8"))
        self.k9.setText(_translate("MainWindow", "9"))
        self.k10.setText(_translate("MainWindow", "10"))
        self.k11.setText(_translate("MainWindow", "11"))
        self.k12.setText(_translate("MainWindow", "12"))
        self.k13.setText(_translate("MainWindow", "13"))
        self.k14.setText(_translate("MainWindow", "14"))
        self.k15.setText(_translate("MainWindow", "15"))
        self.k16.setText(_translate("MainWindow", "16"))
        self.colorLabel2.setText(_translate("MainWindow", "bins_S"))
        self.cellHogLabel.setText(_translate("MainWindow", "Cell size"))
        self.binsHogLabel.setText(_translate("MainWindow", "Hog bins"))
        self.blockHogLabel.setText(_translate("MainWindow", "Block size"))
        self.graph_button.setText(_translate("MainWindow", "MDS plot"))
        self.blockStrideHogLabel.setText(_translate("MainWindow", "Block Stride"))
        self.siftlabel.setText(_translate("MainWindow", "keypoint size"))
        self.entropyLabel_1.setText(_translate("MainWindow", "Enable Entropy"))
        self.entropyLabel_2.setText(_translate("MainWindow", "Enable Entropy"))
        self.histogramButton.setText(_translate("MainWindow", "Calculate features"))
        self.windowHogLabel.setText(_translate("MainWindow", "Detection window size"))
        self.colorLabel1.setText(_translate("MainWindow", "bins_H"))
        self.colorLabel3.setText(_translate("MainWindow", "bins_H"))
        self.colorLabel4.setText(_translate("MainWindow", "bins_S"))
        self.view.setTabText(self.view.indexOf(self.drawTab), _translate("MainWindow", "Draw"))
        self.view.setTabText(self.view.indexOf(self.superpixelTab), _translate("MainWindow", "Superpixel"))
        self.view.setTabText(self.view.indexOf(self.tab), _translate("MainWindow", "Uncertainty"))
        self.view.setTabText(self.view.indexOf(self.resultsTab), _translate("MainWindow", "results"))
        self.view.setTabText(self.view.indexOf(self.tab_2), _translate("MainWindow", "ground truth"))
        self.progressBoxLabel.setText(_translate("MainWindow", "progress box:"))
        self.superpixelLabel.setText(_translate("MainWindow", "superpixel mode"))
        self.exportSettings.setText(_translate("MainWindow", "Export settings"))
        self.edgeRadioButton.setText(_translate("MainWindow", "Edge"))
        self.nodeRadioButton.setText(_translate("MainWindow", "Node"))
        self.graphRadioButton.setText(_translate("MainWindow", "Graph"))
        self.bwRadioButton.setText(_translate("MainWindow", "Black/White"))
        self.bRadioButton.setText(_translate("MainWindow", "Border"))
        self.markingLabel.setText(_translate("MainWindow", "Marking tools"))
        self.drawRadioButton.setText(_translate("MainWindow", "Draw"))
        self.histogramRadioButton.setText(_translate("MainWindow", "MDS"))
        self.fgRadioButton.setText(_translate("MainWindow", "Foreground"))
        self.bgRadioButton.setText(_translate("MainWindow", "Background"))
        self.clearMarkingsButton.setText(_translate("MainWindow", "clear markings"))
        self.importSettings.setText(_translate("MainWindow", "Import Settings"))
        self.cosegmentationProgress.setText(_translate("MainWindow", "Co-segmentation:"))
        self.featureProgress.setText(_translate("MainWindow", "Features:"))
        self.superpixelProgress.setText(_translate("MainWindow", "Superpixels:"))
        self.superpixelStatus.setText(_translate("MainWindow", "Not calculated"))
        self.extractionStatus.setText(_translate("MainWindow", "Not calculated"))
        self.clusteringStatus.setText(_translate("MainWindow", "Not calculated"))
        self.uncertaintyLabel.setText(_translate("MainWindow", "Uncertainty mode"))
        self.graphCutModeLabel.setText(_translate("MainWindow", "Graph cut mode"))
        self.bwkRadioButton.setText(_translate("MainWindow", "Black/white"))
        self.colorRadioButton.setText(_translate("MainWindow", "Color"))
        self.clusterModeLabel.setText(_translate("MainWindow", "kmeans mode"))
        self.gt_overlapRadioButton.setText(_translate("MainWindow", "Overlap"))
        self.gt_originalRadioButton.setText(_translate("MainWindow", "Original"))
        self.gtpercentage.setText(_translate("MainWindow", "N/A %"))
        self.overlapLabel.setText(_translate("MainWindow", "overlap:"))
        self.gtLabel.setText(_translate("MainWindow", "Ground Truth "))


