# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 942)
        MainWindow.setMinimumSize(QtCore.QSize(836, 558))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setMaximumSize(QtCore.QSize(132, 17))
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.superpixelSpinBox = QtWidgets.QSpinBox(self.frame_7)
        self.superpixelSpinBox.setMinimum(1)
        self.superpixelSpinBox.setMaximum(9999)
        self.superpixelSpinBox.setProperty("value", 100)
        self.superpixelSpinBox.setObjectName("superpixelSpinBox")
        self.gridLayout_10.addWidget(self.superpixelSpinBox, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 2, 1, 1, 1)
        self.sigmaSpinBox = QtWidgets.QSpinBox(self.frame_7)
        self.sigmaSpinBox.setMaximum(9999)
        self.sigmaSpinBox.setProperty("value", 5)
        self.sigmaSpinBox.setObjectName("sigmaSpinBox")
        self.gridLayout_10.addWidget(self.sigmaSpinBox, 3, 1, 1, 1)
        self.iterationsSpinBox = QtWidgets.QSpinBox(self.frame_7)
        self.iterationsSpinBox.setMaximum(999)
        self.iterationsSpinBox.setProperty("value", 10)
        self.iterationsSpinBox.setObjectName("iterationsSpinBox")
        self.gridLayout_10.addWidget(self.iterationsSpinBox, 1, 1, 1, 1)
        self.superpixelButton = QtWidgets.QPushButton(self.frame_7)
        self.superpixelButton.setEnabled(False)
        self.superpixelButton.setObjectName("superpixelButton")
        self.gridLayout_10.addWidget(self.superpixelButton, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 2, 0, 1, 1)
        self.compactnessSpinBox = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.compactnessSpinBox.setDecimals(5)
        self.compactnessSpinBox.setProperty("value", 10.0)
        self.compactnessSpinBox.setObjectName("compactnessSpinBox")
        self.gridLayout_10.addWidget(self.compactnessSpinBox, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_7, 4, 0, 1, 1)
        self.clusteringBox = QtWidgets.QComboBox(self.frame_5)
        self.clusteringBox.setObjectName("clusteringBox")
        self.clusteringBox.addItem("")
        self.clusteringBox.addItem("")
        self.clusteringBox.addItem("")
        self.gridLayout_2.addWidget(self.clusteringBox, 3, 0, 1, 1)
        self.graphFrame = QtWidgets.QFrame(self.frame_5)
        self.graphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphFrame.setObjectName("graphFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.graphFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.graphFrame)
        self.doubleSpinBox.setDecimals(5)
        self.doubleSpinBox.setMaximum(999999999.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_7.addWidget(self.doubleSpinBox, 7, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.graphFrame)
        self.doubleSpinBox_2.setDecimals(5)
        self.doubleSpinBox_2.setMaximum(999999999.0)
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_7.addWidget(self.doubleSpinBox_2, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.graphFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 2)
        self.GMMButton = QtWidgets.QPushButton(self.graphFrame)
        self.GMMButton.setEnabled(False)
        self.GMMButton.setObjectName("GMMButton")
        self.gridLayout_7.addWidget(self.GMMButton, 4, 0, 1, 2)
        self.graphcutButton = QtWidgets.QPushButton(self.graphFrame)
        self.graphcutButton.setEnabled(False)
        self.graphcutButton.setObjectName("graphcutButton")
        self.gridLayout_7.addWidget(self.graphcutButton, 8, 0, 1, 2)
        self.componentMax = QtWidgets.QSpinBox(self.graphFrame)
        self.componentMax.setProperty("value", 9)
        self.componentMax.setObjectName("componentMax")
        self.gridLayout_7.addWidget(self.componentMax, 1, 1, 1, 1)
        self.componentMin = QtWidgets.QSpinBox(self.graphFrame)
        self.componentMin.setProperty("value", 5)
        self.componentMin.setObjectName("componentMin")
        self.gridLayout_7.addWidget(self.componentMin, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.graphFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.graphFrame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.graphFrame)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 6, 0, 1, 1)
        self.n_init = QtWidgets.QSpinBox(self.graphFrame)
        self.n_init.setProperty("value", 10)
        self.n_init.setObjectName("n_init")
        self.gridLayout_7.addWidget(self.n_init, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.graphFrame, 8, 0, 1, 1)
        self.kmeansFrame = QtWidgets.QFrame(self.frame_5)
        self.kmeansFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kmeansFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kmeansFrame.setObjectName("kmeansFrame")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.kmeansFrame)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.kmeansButton = QtWidgets.QPushButton(self.kmeansFrame)
        self.kmeansButton.setEnabled(False)
        self.kmeansButton.setObjectName("kmeansButton")
        self.gridLayout_17.addWidget(self.kmeansButton, 1, 0, 1, 1)
        self.kclustervalue = QtWidgets.QSpinBox(self.kmeansFrame)
        self.kclustervalue.setMinimum(2)
        self.kclustervalue.setMaximum(12)
        self.kclustervalue.setObjectName("kclustervalue")
        self.gridLayout_17.addWidget(self.kclustervalue, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.kmeansFrame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_17.addWidget(self.label_10, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.kmeansFrame, 9, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.Hog = QtWidgets.QCheckBox(self.frame_2)
        self.Hog.setObjectName("Hog")
        self.gridLayout_19.addWidget(self.Hog, 0, 2, 1, 1)
        self.HueSat = QtWidgets.QCheckBox(self.frame_2)
        self.HueSat.setObjectName("HueSat")
        self.gridLayout_19.addWidget(self.HueSat, 1, 1, 1, 1)
        self.RGB = QtWidgets.QCheckBox(self.frame_2)
        self.RGB.setChecked(True)
        self.RGB.setObjectName("RGB")
        self.gridLayout_19.addWidget(self.RGB, 0, 0, 1, 1)
        self.Saturation = QtWidgets.QCheckBox(self.frame_2)
        self.Saturation.setObjectName("Saturation")
        self.gridLayout_19.addWidget(self.Saturation, 0, 1, 1, 1)
        self.HSV = QtWidgets.QCheckBox(self.frame_2)
        self.HSV.setObjectName("HSV")
        self.gridLayout_19.addWidget(self.HSV, 1, 0, 1, 1)
        self.Sift = QtWidgets.QCheckBox(self.frame_2)
        self.Sift.setObjectName("Sift")
        self.gridLayout_19.addWidget(self.Sift, 2, 1, 1, 1)
        self.Hue = QtWidgets.QCheckBox(self.frame_2)
        self.Hue.setObjectName("Hue")
        self.gridLayout_19.addWidget(self.Hue, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_19.addWidget(self.label_14, 3, 0, 1, 1)
        self.featureSelected = QtWidgets.QComboBox(self.frame_2)
        self.featureSelected.setObjectName("featureSelected")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.addItem("")
        self.featureSelected.setItemText(7, "")
        self.gridLayout_19.addWidget(self.featureSelected, 3, 1, 1, 2)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.colorLabel2 = QtWidgets.QLabel(self.frame_8)
        self.colorLabel2.setObjectName("colorLabel2")
        self.gridLayout_12.addWidget(self.colorLabel2, 5, 0, 1, 1)
        self.cellHogLabel = QtWidgets.QLabel(self.frame_8)
        self.cellHogLabel.setObjectName("cellHogLabel")
        self.gridLayout_12.addWidget(self.cellHogLabel, 13, 1, 1, 1)
        self.hogBins = QtWidgets.QSpinBox(self.frame_8)
        self.hogBins.setObjectName("hogBins")
        self.gridLayout_12.addWidget(self.hogBins, 16, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 17, 0, 1, 1)
        self.binsHogLabel = QtWidgets.QLabel(self.frame_8)
        self.binsHogLabel.setObjectName("binsHogLabel")
        self.gridLayout_12.addWidget(self.binsHogLabel, 15, 0, 1, 1)
        self.cellSize = QtWidgets.QSpinBox(self.frame_8)
        self.cellSize.setObjectName("cellSize")
        self.gridLayout_12.addWidget(self.cellSize, 14, 1, 1, 1)
        self.blockHogLabel = QtWidgets.QLabel(self.frame_8)
        self.blockHogLabel.setObjectName("blockHogLabel")
        self.gridLayout_12.addWidget(self.blockHogLabel, 11, 1, 1, 1)
        self.winSize = QtWidgets.QSpinBox(self.frame_8)
        self.winSize.setObjectName("winSize")
        self.gridLayout_12.addWidget(self.winSize, 12, 0, 1, 1)
        self.blockStride = QtWidgets.QSpinBox(self.frame_8)
        self.blockStride.setObjectName("blockStride")
        self.gridLayout_12.addWidget(self.blockStride, 14, 0, 1, 1)
        self.blockSize = QtWidgets.QSpinBox(self.frame_8)
        self.blockSize.setObjectName("blockSize")
        self.gridLayout_12.addWidget(self.blockSize, 12, 1, 1, 1)
        self.graph_button = QtWidgets.QPushButton(self.frame_8)
        self.graph_button.setEnabled(False)
        self.graph_button.setObjectName("graph_button")
        self.gridLayout_12.addWidget(self.graph_button, 18, 1, 1, 1)
        self.blockStrideHogLabel = QtWidgets.QLabel(self.frame_8)
        self.blockStrideHogLabel.setObjectName("blockStrideHogLabel")
        self.gridLayout_12.addWidget(self.blockStrideHogLabel, 13, 0, 1, 1)
        self.siftlabel = QtWidgets.QLabel(self.frame_8)
        self.siftlabel.setObjectName("siftlabel")
        self.gridLayout_12.addWidget(self.siftlabel, 8, 0, 1, 1)
        self.HHist = QtWidgets.QSpinBox(self.frame_8)
        self.HHist.setMaximum(360)
        self.HHist.setProperty("value", 5)
        self.HHist.setObjectName("HHist")
        self.gridLayout_12.addWidget(self.HHist, 3, 0, 1, 1)
        self.HSSHist = QtWidgets.QSpinBox(self.frame_8)
        self.HSSHist.setMinimum(2)
        self.HSSHist.setMaximum(360)
        self.HSSHist.setProperty("value", 3)
        self.HSSHist.setObjectName("HSSHist")
        self.gridLayout_12.addWidget(self.HSSHist, 1, 1, 1, 1)
        self.entropyLabel_1 = QtWidgets.QLabel(self.frame_8)
        self.entropyLabel_1.setObjectName("entropyLabel_1")
        self.gridLayout_12.addWidget(self.entropyLabel_1, 2, 1, 1, 1)
        self.SHist = QtWidgets.QSpinBox(self.frame_8)
        self.SHist.setMinimum(2)
        self.SHist.setMaximum(360)
        self.SHist.setProperty("value", 3)
        self.SHist.setObjectName("SHist")
        self.gridLayout_12.addWidget(self.SHist, 6, 0, 1, 1)
        self.entropyLabel_2 = QtWidgets.QLabel(self.frame_8)
        self.entropyLabel_2.setObjectName("entropyLabel_2")
        self.gridLayout_12.addWidget(self.entropyLabel_2, 5, 1, 1, 1)
        self.histogramButton = QtWidgets.QPushButton(self.frame_8)
        self.histogramButton.setEnabled(False)
        self.histogramButton.setObjectName("histogramButton")
        self.gridLayout_12.addWidget(self.histogramButton, 18, 0, 1, 1)
        self.siftKeyPoint = QtWidgets.QSpinBox(self.frame_8)
        self.siftKeyPoint.setMinimum(1)
        self.siftKeyPoint.setProperty("value", 32)
        self.siftKeyPoint.setObjectName("siftKeyPoint")
        self.gridLayout_12.addWidget(self.siftKeyPoint, 9, 0, 1, 1)
        self.windowHogLabel = QtWidgets.QLabel(self.frame_8)
        self.windowHogLabel.setObjectName("windowHogLabel")
        self.gridLayout_12.addWidget(self.windowHogLabel, 11, 0, 1, 1)
        self.colorLabel1 = QtWidgets.QLabel(self.frame_8)
        self.colorLabel1.setObjectName("colorLabel1")
        self.gridLayout_12.addWidget(self.colorLabel1, 2, 0, 1, 1)
        self.SentropyCheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.SentropyCheckBox.setText("")
        self.SentropyCheckBox.setObjectName("SentropyCheckBox")
        self.gridLayout_12.addWidget(self.SentropyCheckBox, 6, 1, 1, 1)
        self.HSHHist = QtWidgets.QSpinBox(self.frame_8)
        self.HSHHist.setMinimum(2)
        self.HSHHist.setMaximum(360)
        self.HSHHist.setProperty("value", 5)
        self.HSHHist.setObjectName("HSHHist")
        self.gridLayout_12.addWidget(self.HSHHist, 1, 0, 1, 1)
        self.HentropyCheckBox = QtWidgets.QCheckBox(self.frame_8)
        self.HentropyCheckBox.setText("")
        self.HentropyCheckBox.setObjectName("HentropyCheckBox")
        self.gridLayout_12.addWidget(self.HentropyCheckBox, 3, 1, 1, 1)
        self.colorLabel3 = QtWidgets.QLabel(self.frame_8)
        self.colorLabel3.setObjectName("colorLabel3")
        self.gridLayout_12.addWidget(self.colorLabel3, 0, 0, 1, 1)
        self.colorLabel4 = QtWidgets.QLabel(self.frame_8)
        self.colorLabel4.setObjectName("colorLabel4")
        self.gridLayout_12.addWidget(self.colorLabel4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_8, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(350, 350))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.treeView = QtWidgets.QTreeView(self.frame)
        self.treeView.setObjectName("treeView")
        self.gridLayout_4.addWidget(self.treeView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 350))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.frame_4)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 776, 93))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_4)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_24.addWidget(self.listWidget, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 2, 1, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.drawTab = QtWidgets.QWidget()
        self.drawTab.setObjectName("drawTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.drawTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.drawTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 603, 723))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout_6.addWidget(self.image, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.drawTab, "")
        self.superpixelTab = QtWidgets.QWidget()
        self.superpixelTab.setObjectName("superpixelTab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.superpixelTab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.superpixelTab)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 603, 723))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.superImage = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.superImage.setText("")
        self.superImage.setObjectName("superImage")
        self.gridLayout_16.addWidget(self.superImage, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_15.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.superpixelTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 603, 723))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.uncertaintyImage = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.uncertaintyImage.setText("")
        self.uncertaintyImage.setObjectName("uncertaintyImage")
        self.gridLayout_22.addWidget(self.uncertaintyImage, 0, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_23.addWidget(self.scrollArea_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.resultsTab = QtWidgets.QWidget()
        self.resultsTab.setObjectName("resultsTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.resultsTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.resultsTab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 603, 723))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.result_image = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.result_image.setText("")
        self.result_image.setObjectName("result_image")
        self.gridLayout_14.addWidget(self.result_image, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_8.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.resultsTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(178, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_29.setObjectName("label_29")
        self.gridLayout_13.addWidget(self.label_29, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_13.addWidget(self.pushButton_3, 11, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.edgeRadioButton = QtWidgets.QRadioButton(self.frame_6)
        self.edgeRadioButton.setEnabled(False)
        self.edgeRadioButton.setCheckable(True)
        self.edgeRadioButton.setChecked(True)
        self.edgeRadioButton.setObjectName("edgeRadioButton")
        self.gridLayout_11.addWidget(self.edgeRadioButton, 0, 0, 1, 1)
        self.nodeRadioButton = QtWidgets.QRadioButton(self.frame_6)
        self.nodeRadioButton.setEnabled(False)
        self.nodeRadioButton.setCheckable(True)
        self.nodeRadioButton.setObjectName("nodeRadioButton")
        self.gridLayout_11.addWidget(self.nodeRadioButton, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.frame_6, 5, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.bwRadioButton = QtWidgets.QRadioButton(self.frame_9)
        self.bwRadioButton.setEnabled(False)
        self.bwRadioButton.setChecked(True)
        self.bwRadioButton.setObjectName("bwRadioButton")
        self.gridLayout_18.addWidget(self.bwRadioButton, 0, 0, 1, 1)
        self.bRadioButton = QtWidgets.QRadioButton(self.frame_9)
        self.bRadioButton.setEnabled(False)
        self.bRadioButton.setObjectName("bRadioButton")
        self.gridLayout_18.addWidget(self.bRadioButton, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.frame_9, 7, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_28.setObjectName("label_28")
        self.gridLayout_13.addWidget(self.label_28, 0, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.drawRadioButton = QtWidgets.QRadioButton(self.frame_12)
        self.drawRadioButton.setEnabled(False)
        self.drawRadioButton.setChecked(True)
        self.drawRadioButton.setObjectName("drawRadioButton")
        self.gridLayout_9.addWidget(self.drawRadioButton, 0, 0, 1, 1)
        self.histogramRadioButton = QtWidgets.QRadioButton(self.frame_12)
        self.histogramRadioButton.setEnabled(False)
        self.histogramRadioButton.setObjectName("histogramRadioButton")
        self.gridLayout_9.addWidget(self.histogramRadioButton, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_12, 3, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 360))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.clearMarkingsButton = QtWidgets.QPushButton(self.frame_10)
        self.clearMarkingsButton.setEnabled(False)
        self.clearMarkingsButton.setObjectName("clearMarkingsButton")
        self.gridLayout_20.addWidget(self.clearMarkingsButton, 5, 0, 1, 1)
        self.markSize = QtWidgets.QSpinBox(self.frame_10)
        self.markSize.setMinimum(1)
        self.markSize.setObjectName("markSize")
        self.gridLayout_20.addWidget(self.markSize, 4, 0, 1, 1)
        self.eRadioButton = QtWidgets.QRadioButton(self.frame_10)
        self.eRadioButton.setObjectName("eRadioButton")
        self.gridLayout_20.addWidget(self.eRadioButton, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_10)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_21.setObjectName("label_21")
        self.gridLayout_20.addWidget(self.label_21, 3, 0, 1, 1)
        self.bgRadioButton = QtWidgets.QRadioButton(self.frame_10)
        self.bgRadioButton.setObjectName("bgRadioButton")
        self.gridLayout_20.addWidget(self.bgRadioButton, 1, 0, 1, 1)
        self.fgRadioButton = QtWidgets.QRadioButton(self.frame_10)
        self.fgRadioButton.setChecked(True)
        self.fgRadioButton.setObjectName("fgRadioButton")
        self.gridLayout_20.addWidget(self.fgRadioButton, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_10, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_13.addWidget(self.pushButton_4, 10, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.extractionStatus = QtWidgets.QLabel(self.frame_11)
        self.extractionStatus.setObjectName("extractionStatus")
        self.gridLayout_21.addWidget(self.extractionStatus, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_11)
        self.label_26.setObjectName("label_26")
        self.gridLayout_21.addWidget(self.label_26, 4, 0, 1, 1)
        self.superpixelStatus = QtWidgets.QLabel(self.frame_11)
        self.superpixelStatus.setObjectName("superpixelStatus")
        self.gridLayout_21.addWidget(self.superpixelStatus, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_11)
        self.label_23.setObjectName("label_23")
        self.gridLayout_21.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_11)
        self.label_22.setObjectName("label_22")
        self.gridLayout_21.addWidget(self.label_22, 0, 0, 1, 1)
        self.clusteringStatus = QtWidgets.QLabel(self.frame_11)
        self.clusteringStatus.setObjectName("clusteringStatus")
        self.gridLayout_21.addWidget(self.clusteringStatus, 5, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_11, 9, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_13.addWidget(self.label_16, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Clustering"))
        self.label_11.setText(_translate("MainWindow", "Feature extraction"))
        self.label.setText(_translate("MainWindow", "Superpixel quantity"))
        self.label_5.setText(_translate("MainWindow", "Sigma"))
        self.superpixelButton.setText(_translate("MainWindow", "Calculate superpixels"))
        self.label_3.setText(_translate("MainWindow", "Iterations"))
        self.label_4.setText(_translate("MainWindow", "Compactness"))
        self.clusteringBox.setItemText(0, _translate("MainWindow", "Graph Cut"))
        self.clusteringBox.setItemText(1, _translate("MainWindow", "kmeans clustering"))
        self.clusteringBox.setItemText(2, _translate("MainWindow", "Spectral clustering"))
        self.label_7.setText(_translate("MainWindow", "Component range"))
        self.GMMButton.setText(_translate("MainWindow", "Compute GMM and uncertainties"))
        self.graphcutButton.setText(_translate("MainWindow", "Graph cut"))
        self.label_6.setText(_translate("MainWindow", "Number of restarts"))
        self.label_13.setText(_translate("MainWindow", "scale parameters"))
        self.label_12.setText(_translate("MainWindow", "pairwise term scale"))
        self.kmeansButton.setText(_translate("MainWindow", "kmeans clustering"))
        self.label_10.setText(_translate("MainWindow", "Clusters"))
        self.Hog.setText(_translate("MainWindow", "Hog"))
        self.HueSat.setText(_translate("MainWindow", "Hue x Saturation"))
        self.RGB.setText(_translate("MainWindow", "RGB"))
        self.Saturation.setText(_translate("MainWindow", "Saturation"))
        self.HSV.setText(_translate("MainWindow", "HSV"))
        self.Sift.setText(_translate("MainWindow", "Sift"))
        self.Hue.setText(_translate("MainWindow", "Hue"))
        self.label_14.setText(_translate("MainWindow", "Current:"))
        self.featureSelected.setItemText(0, _translate("MainWindow", "RGB"))
        self.featureSelected.setItemText(1, _translate("MainWindow", "HSV"))
        self.featureSelected.setItemText(2, _translate("MainWindow", "Hue"))
        self.featureSelected.setItemText(3, _translate("MainWindow", "Saturation"))
        self.featureSelected.setItemText(4, _translate("MainWindow", "Hue x Saturation"))
        self.featureSelected.setItemText(5, _translate("MainWindow", "Sift"))
        self.featureSelected.setItemText(6, _translate("MainWindow", "Hog"))
        self.colorLabel2.setText(_translate("MainWindow", "bins_S"))
        self.cellHogLabel.setText(_translate("MainWindow", "Cell size"))
        self.binsHogLabel.setText(_translate("MainWindow", "Hog bins"))
        self.blockHogLabel.setText(_translate("MainWindow", "Block size"))
        self.graph_button.setText(_translate("MainWindow", "MDS graph"))
        self.blockStrideHogLabel.setText(_translate("MainWindow", "Block Stride"))
        self.siftlabel.setText(_translate("MainWindow", "keypoint size"))
        self.entropyLabel_1.setText(_translate("MainWindow", "Enable Entropy"))
        self.entropyLabel_2.setText(_translate("MainWindow", "Enable Entropy"))
        self.histogramButton.setText(_translate("MainWindow", "Calculate histograms"))
        self.windowHogLabel.setText(_translate("MainWindow", "Detection window size"))
        self.colorLabel1.setText(_translate("MainWindow", "bins_H"))
        self.colorLabel3.setText(_translate("MainWindow", "bins_H"))
        self.colorLabel4.setText(_translate("MainWindow", "bins_S"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.drawTab), _translate("MainWindow", "Draw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.superpixelTab), _translate("MainWindow", "Superpixel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Uncertainty"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resultsTab), _translate("MainWindow", "results"))
        self.label_29.setText(_translate("MainWindow", "progress box:"))
        self.label_9.setText(_translate("MainWindow", "superpixel setting:"))
        self.pushButton_3.setText(_translate("MainWindow", "Export settings"))
        self.edgeRadioButton.setText(_translate("MainWindow", "Edge"))
        self.nodeRadioButton.setText(_translate("MainWindow", "Node"))
        self.bwRadioButton.setText(_translate("MainWindow", "black white mode"))
        self.bRadioButton.setText(_translate("MainWindow", "border mode"))
        self.label_28.setText(_translate("MainWindow", "Marking tools:"))
        self.drawRadioButton.setText(_translate("MainWindow", "Draw mode"))
        self.histogramRadioButton.setText(_translate("MainWindow", "Histogram mode"))
        self.clearMarkingsButton.setText(_translate("MainWindow", "clear markings"))
        self.eRadioButton.setText(_translate("MainWindow", "Eraser"))
        self.label_21.setText(_translate("MainWindow", "pen Size"))
        self.bgRadioButton.setText(_translate("MainWindow", "Background"))
        self.fgRadioButton.setText(_translate("MainWindow", "Foreground"))
        self.pushButton_4.setText(_translate("MainWindow", "Import Settings"))
        self.extractionStatus.setText(_translate("MainWindow", "Not calculated"))
        self.label_26.setText(_translate("MainWindow", "clustering:"))
        self.superpixelStatus.setText(_translate("MainWindow", "Not calculated"))
        self.label_23.setText(_translate("MainWindow", "Extractions"))
        self.label_22.setText(_translate("MainWindow", "Superpixels:"))
        self.clusteringStatus.setText(_translate("MainWindow", "Not calculated"))
        self.label_15.setText(_translate("MainWindow", "Uncertainty mode"))
        self.label_16.setText(_translate("MainWindow", "Graph cut mode"))


